# Generated by Django 3.1.7 on 2021-03-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('config_json', models.TextField(default='')),
                ('session_wide_url', models.CharField(max_length=255)),
                ('admin_url', models.CharField(max_length=255)),
                ('num_participants', models.IntegerField()),
                ('max_assignments', models.IntegerField(null=True)),
                ('use_sandbox', models.BooleanField(null=True)),
                ('expiration', models.FloatField(null=True)),
                ('HITGroupId', models.CharField(default='', max_length=255)),
                ('question_template', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HITWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=255)),
                ('worker_id', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HIT',
            fields=[
                ('hit_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('HITGroupId', models.CharField(max_length=255)),
                ('max_assignments', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
