# Generated by Django 3.1.7 on 2021-03-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20210316_1201'),
        ('mturk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hr.site'),
        ),
    ]
