# Generated by Django 3.1.7 on 2021-06-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20210614_0923'),
        ('mturk', '0002_auto_20210316_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('site', 'code')},
        ),
    ]
