# Generated by Django 3.1.7 on 2021-03-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20210310_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aws_access_key_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS_ACCESS_KEY_ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aws_secret_access_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS_SECRET_ACCESS_KEY'),
        ),
        migrations.AlterField(
            model_name='site',
            name='rest_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='OTREE_REST_KEY'),
        ),
    ]
