# Generated by Django 3.1.7 on 2021-07-09 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20210622_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aws_keys_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='rest_key_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
