# Generated by Django 3.1.7 on 2021-03-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolific', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='study_id',
        ),
        migrations.AddField(
            model_name='session',
            name='completion_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Completion URL'),
        ),
    ]
